```{r setup, cache=FALSE, include=FALSE}
library(knitr)
opts_chunk$set(fig.width=11, fig.height=7, base64_images=F, fig.align="center", message=F, warning=F, fig.path='figure_cwt/')
```


# Wavelet Scale Correspondance
```{r}
library(centWaveP)
```

```{r}

for (i in seq(1, 50, 5)) {
  wav = centWaveP:::return.wavelet('mexh') %>% { centWaveP:::scale.wavelet(i, .)$y }
  plot(wav)
  cat(sum(wav > 0), i, "\n")
  }
```

```{r}
for (i in seq(1, 50, 5)) {
  wav = centWaveP:::return.wavelet('nmexh') %>% { centWaveP:::scale.wavelet(i, .)$y }
  plot(wav)
  cat(sum(wav < 0), i, "\n")
  }
```

```{r}

eic = { dnorm(seq(-6, 6, by =0.1)) } %>% { ./max(.) }
plot(eic)


for (i in seq(1, 50, 5)) {
  wav = cwt(eic, i, 'mexh')
  print(plot(wav, main = i))
  cat(sum(wav > 0), i, "\n")
}
```

```{r}

eic = { dnorm(seq(-6, 6, by =0.1)) + dnorm(seq(-6, 6, by =0.1), mean = 3) } %>% { ./max(.) }
plot(eic)


for (i in seq(1, 50, 5)) {
  wav = cwt(eic, i, 'nmexh')
  print(plot(wav, main = i))
  cat(sum(wav < 0), i, "\n")
}
```